"""Regenerate scripts/<Sprite>.txt from nightguard_extract/project.json, matching
the existing "Regenerated by session tooling" format used for Door.txt/Office.txt/etc.
Usage: python regen_scripts_txt.py Door CamMenu ...
"""
import sys
sys.path.insert(0, ".")
import json
from pretty_print import dump_target

WORK = "nightguard_extract"
proj_path = WORK + "/project.json"
data = json.load(open(proj_path, encoding="utf-8"))

HEADER = "//----- Regenerated by session tooling from the final patched project.json -----------------------------------------"


def target(name):
    return next(t for t in data["targets"] if t["name"] == name)


def render(name):
    t = target(name)
    body = dump_target(t).rstrip("\n")
    costumes = "\n".join(f"{c['name']}.{c.get('dataFormat', 'svg')}" for c in t["costumes"])
    sounds = "\n".join(f"{s['name']}.{s.get('dataFormat', 'wav')}" for s in t["sounds"])
    parts = [HEADER, "", body, "", ""]
    parts.append("//----- Costumes ------------------------------------------------------------------------------------------------------")
    parts.append("")
    parts.append(costumes)
    parts.append("")
    parts.append("")
    if sounds:
        parts.append("//----- Sounds --------------------------------------------------------------------------------------------------------")
        parts.append("")
        parts.append(sounds)
        parts.append("")
    return "\n".join(parts)


for name in sys.argv[1:]:
    out_path = f"../scripts/{name}.txt"
    text = render(name)
    open(out_path, "w", encoding="utf-8", newline="\n").write(text)
    print(f"wrote {out_path} ({len(text)} bytes)")
