"""Repack nightguard_extract/project.json back into ../sb3/1287939979.sb3.

Rebuilds the zip from scratch: project.json plus every asset it actually
references (sounds + costumes). Replacing audio (install_phone_guy.py /
swap_phone_sounds.py) therefore drops the old clips instead of leaving
orphaned <md5>.mp3 entries behind. Asset bytes come from the current sb3 when
they're unchanged, otherwise from the staged assets in dev/phone_audio/
(md5-named files generated by gen_phone_audio.py, gitignored).
"""
import glob
import json
import os
import zipfile

SB3 = "../sb3/1287939979.sb3"
PROJECT_JSON = "nightguard_extract/project.json"
TMP = SB3 + ".tmp"
ASSET_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "phone_audio")


def referenced_assets(project_json_bytes):
    data = json.loads(project_json_bytes)
    names = set()
    for t in data["targets"]:
        for s in t.get("sounds", []):
            names.add(s["md5ext"])
        for c in t.get("costumes", []):
            names.add(c["md5ext"])
    return names


def staged_assets():
    return {
        os.path.basename(p)
        for p in glob.glob(os.path.join(ASSET_DIR, "[0-9a-f]" * 32 + ".*"))
    }


with open(PROJECT_JSON, "rb") as f:
    new_project_json = f.read()

need = referenced_assets(new_project_json)
have = staged_assets()

with zipfile.ZipFile(SB3, "r") as zin:
    old = {item.filename: zin.read(item.filename) for item in zin.infolist()}

missing = need - set(old) - have
if missing:
    raise SystemExit(f"assets referenced but unavailable: {sorted(missing)})")

with zipfile.ZipFile(TMP, "w", zipfile.ZIP_DEFLATED) as zout:
    zout.writestr("project.json", new_project_json, compress_type=zipfile.ZIP_DEFLATED)
    for name in sorted(need):
        data = old.get(name)
        if data is None:
            with open(os.path.join(ASSET_DIR, name), "rb") as f:
                data = f.read()
        zout.writestr(name, data, compress_type=zipfile.ZIP_DEFLATED)

os.replace(TMP, SB3)
dropped = sorted(set(old) - need - {"project.json"})
print(f"Repacked {SB3}: {len(need)} referenced assets + project.json")
if dropped:
    print(f"dropped {len(dropped)} unreferenced asset(s): {dropped}")

with zipfile.ZipFile(SB3) as z:
    bad = z.testzip()
    assert bad is None, f"corrupt entry: {bad}"
    names = z.namelist()
    dupes = {n for n in names if names.count(n) > 1}
    assert not dupes, f"duplicate zip entries: {dupes}"
    assert len(z.read("project.json")) == len(new_project_json)
    print("Repack verified OK.")